# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'vkontakteVS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for vkontakteVS
pod 'Firebase/Database'
pod 'Firebase/Storage'

  target 'vkontakteVSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'vkontakteVSUITests' do
    # Pods for testing
  end

end
